name: Build and Push Docker Images

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Elasticsearch Docker Image
        uses: docker/build-push-action@v2
        with:
          context: setup-elasticsearch/
          file: setup-elasticsearch/Dockerfile
          push: true
          tags: ghcr.io/vhrechukha/elasticsearch:${{ github.sha }}

      - name: Build Rust App Docker Image
        uses: docker/build-push-action@v2
        with:
          context: app/
          file: app/Dockerfile
          push: true
          tags: ghcr.io/vhrechukha/rust-app:${{ github.sha }}

      - name: Run Docker Compose
        run: |
          docker-compose -f docker-compose.yml up -d --build

