name: Build and Push Docker image

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch
    tags:
      - 'v*'  # Trigger on tag pushes that match v*

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to GitHub Docker Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/my-image:${{ github.sha }}
          labels: |
            org.opencontainers.image.source=${{ github.event.repository.html_url }}
            org.opencontainers.image.created=${{ steps.date.outputs.date }}
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.version=${{ github.ref }}

      - name: Set up Cloud SDK
        if: env.PROJECT_ID != ''  # Only run if PROJECT_ID is set
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          project_id: ${{ env.PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Push to Google Container Registry
        if: env.PROJECT_ID != ''  # Only run if PROJECT_ID is set
        run: |
          echo "Pushing image to Google Cloud..."
          docker push ghcr.io/${{ github.repository_owner }}/my-image:${{ github.sha }}

# Environment variables
env:
  PROJECT_ID: mosend  # Set your project ID here

