name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  PROJECT_ID: mosend
  IMAGE_REPO_NAME: vhrechukha/elasticsearch-rust-autocomplete

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Google Container Registry
      uses: google-github-actions/setup-gcloud@master
      with:
        version: 'latest'
        project_id: ${{ env.PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
      continue-on-error: false

    - name: Configure Docker Meta Data
      id: docker_meta
      uses: docker/metadata-action@v3
      with:
        images: gcr.io/${{ env.PROJECT_ID }}/${{ env.IMAGE_REPO_NAME }}
        tags: |
          type=sha,prefix=sha-,format=long
          type=ref,event=branch
          type=ref,event=pr

    - name: Build and Push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ steps.docker_meta.outputs.tags }}
        labels: ${{ steps.docker_meta.outputs.labels }}

    - name: Output the Built Image
      run: echo "Built image ${{ steps.docker_meta.outputs.tags }}"
